Prj_CSharpGo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Prj_CSharpGo.Models;
using Prj_CSharpGo.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Prj_CSharpGo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private WildnessCampingContext _context;

        public HomeController(ILogger<HomeController> logger, WildnessCampingContext dbContext)
        {
            _logger = logger;
            _context = dbContext;
        }

        public IActionResult Index()
        {

            ProductHome productHome = new ProductHome
            {
                products = _context.Products.ToList(),
                productImgs = _context.ProductImgs.ToList(),
                categories = _context.Categories.ToList(),
                categoriesTypeIs = _context.CategoriesTypeIs.ToList(),
                categoriesTypeIis = _context.CategoriesTypeIis.ToList()
            };

            // 寫入Session 
            //string userSession = HttpContext.Session.GetString("userName") ?? "Guest";
            //if (userSession == "Guest")
            //{
            //    return View(productHome);
            //}
            //HttpContext.Session.SetString("userToastr", "已登入");

            
            return View(productHome);
        }

        public IActionResult ProductCate()
        {
            return View();
        }

        // 正常來說會收到一段string productid 但是目前頁面還沒處理好 我就直接給 productid = "Aa10CL007"
        public IActionResult Product(string productid, string categoryid)
        {

            productid = "Aa10CL007";
            categoryid = "A";

            // 新創個類別 類別在~/Model/ViewModels/ProductHome.cs 修改類別的話Jane DiDI要討論一下 建議是從下面{}取得的值修改就好
            ProductHome productHome = new ProductHome
            {
                products = from o in _context.Products
                           where o.ProductId == productid 
                           select o,
                productImgs = from o in _context.ProductImgs
                              where o.ProductId == productid
                              select o ,
                categories = from o in _context.Categories
                             where o.CategoryId == categoryid
                             select o,
                categoriesTypeIs = _context.CategoriesTypeIs.ToList(),
                categoriesTypeIis = _context.CategoriesTypeIis.ToList()
            };
            return View(productHome);
        }

        public IActionResult ProductsList(string? CategoryId, string? CategoryTypeId)
        {
            
            ProductHome productHome = new ProductHome
            {
                products = _context.Products.ToList(),
                productImgs = _context.ProductImgs.ToList(),
                categories = _context.Categories.ToList(),
                categoriesTypeIs = _context.CategoriesTypeIs.ToList(),
                categoriesTypeIis = _context.CategoriesTypeIis.ToList()
            };
            Console.WriteLine("CategoryId:" + CategoryId);
            Console.WriteLine("CategoryTypeId:" + CategoryTypeId);

            if (CategoryId != null && CategoryId != "0")
            {
                productHome.products = _context.Products.Where(x => x.CategoryId == CategoryId);
            }

            if (CategoryTypeId != null && CategoryTypeId != "0")
            {
                productHome.products = _context.Products.Where(x => x.CategoryId == CategoryId);
            }
            if(CategoryId !=null && CategoryTypeId != null)
            {
                productHome.products = _context.Products.Where(x => x.CategoryType == CategoryTypeId);
            }
            return View(productHome);
        }

        public IActionResult Talk(string productid)
        {


            return View();
        }


        //內建 無視掉
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Prj_CSharpGo/Controllers/PShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Prj_CSharpGo.Models;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using Prj_CSharpGo.Models.ShopCartViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace Prj_CSharpGo.Controllers
{
    public class PShopCartController : Controller
    {
        private readonly ILogger<PShopCartController> _logger;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly WildnessCampingContext _context;
        public PShopCartController(WildnessCampingContext context, ILogger<PShopCartController> logger, Microsoft.AspNetCore.Hosting.IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;
        }

        public ActionResult Home()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<ShoppingCart>>> myCart()
        {
            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }

            var shopcart = _context.ShoppingCarts.Where(x => x.UserId.ToString() == userId);
            return await shopcart.ToListAsync();
        }


        [HttpPost]
        public IActionResult dash(string ProductId)
        {
            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }

            var dash0 = _context.ShoppingCarts.Where(x => x.UserId.ToString() == userId);

            var _dash = dash0.Where(x => x.ProductId == ProductId).ToList()[0];
            if (_dash == null)
            {
                return NotFound();
            }
            if (_dash.Quantity == null)
            {
                return NotFound();
            }

            if (_dash.Quantity > 1)
            {
                _dash.Quantity -= 1;
                _context.SaveChanges();
            }

            return Redirect("/PShopCart/Index");
        }
        [HttpPost]
        public IActionResult plus(string ProductId)
        {
            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }
            var dash0 = _context.ShoppingCarts.Where(x => x.UserId.ToString() == userId);

            var _dash = dash0.Where(x => x.ProductId == ProductId).ToList()[0];
            if (_dash == null)
            {
                return NotFound();
            }
            if (_dash.Quantity == null)
            {
                return NotFound();
            }

            if (_dash.Quantity < _context.Products.Find(ProductId).UnitInStock)
            {
                _dash.Quantity += 1;
                _context.SaveChanges();
            }


            ViewBag.messagea = "已完成訂單";
            return Redirect("/PShopCart/Index");
        }
        [HttpPost]
        public IActionResult delete(string ProductId)
        {
            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }
            var dash0 = _context.ShoppingCarts.Where(x => x.UserId.ToString() == userId);

            var _dash = dash0.Where(x => x.ProductId == ProductId).ToList()[0];
            if (_dash == null)
            {
                return NotFound();
            }
            if (_dash.Quantity == null)
            {
                return NotFound();
            }

            _context.ShoppingCarts.Remove(_dash);
            _context.SaveChanges();

            return Redirect("/PShopCart/Index");
        }
        [HttpPost]
        public IActionResult Bill([Bind("OrderID,UserID,TotalPrice,PayMethod,OrderDate,Approval,Address,UserName")] Order order)
        {
            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }
            var dash0 = _context.ShoppingCarts.Where(x => x.UserId.ToString() == userId).ToList();


            if (dash0 == null)
            {
                return NotFound();
            }

            order.UserId = Convert.ToInt32(userId);
            order.OrderDate = DateTime.Now;
            order.TotalPrice = 0;
            foreach (var item in dash0)
            {
                order.TotalPrice += item.Quantity*item.UnitPrice;

            }
            
            
            if (order.TotalPrice == 0)
            {
                HttpContext.Session.SetString("shopcart", "購物車沒有東西");
                return Redirect("/PShopCart/Index");
            }
            order.Approval = "SP";
            _context.Orders.Add(order);
            _context.SaveChanges();

            var query = (from o in _context.Orders
                        where o.UserId.ToString() == userId
                        orderby o.OrderDate descending
                        select o).FirstOrDefault();
            
            foreach (var item in dash0)
            {
                OrderDetail orderDetail=new();
                orderDetail.OrderId = query.OrderId;
                orderDetail.ProductId = item.ProductId;
                orderDetail.UnitPrice = item.UnitPrice;
                orderDetail.Quantity = item.Quantity;
                _context.OrderDetails.Add(orderDetail);
                _context.SaveChanges();
            }


            foreach (var item in dash0)
            {
                _context.ShoppingCarts.Remove(item);
            }
            _context.SaveChanges();

            HttpContext.Session.SetString("shopcart", "訂單已產生");

            return Redirect($"/Auth/MemberOrderEdit/{query.OrderId}");

        }

        //以下是購物車相關------------------------------------------------------------------------------------
        [HttpPost]
        public IActionResult AddCart(ShoppingCart ShoppingCarts,string notgocart)//檢視：無-接收商品頁面的資料 要傳進購物車資料庫PShopCartViewMolds中的ShoppingCarts的動作
        {
            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }

            if (_context.ShoppingCarts.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId) != null)
            {
                _context.ShoppingCarts.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId).Quantity += ShoppingCarts.Quantity;
                if (_context.ShoppingCarts.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId).Quantity > _context.Products.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId).UnitInStock)
                { _context.ShoppingCarts.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId).Quantity = _context.Products.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId).UnitInStock; }
            }
            else
            {
                if(ShoppingCarts.Quantity > _context.Products.FirstOrDefault(x=>x.ProductId== ShoppingCarts.ProductId).UnitInStock) 
                { ShoppingCarts.Quantity = _context.Products.FirstOrDefault(x => x.ProductId == ShoppingCarts.ProductId).UnitInStock; }
                ShoppingCart PTOSCOrder = new ShoppingCart()
                {
                    UserId = ShoppingCarts.UserId,
                    ProductId = ShoppingCarts.ProductId,
                    Quantity = ShoppingCarts.Quantity,
                    Status = ShoppingCarts.Status,
                    ProductName = ShoppingCarts.ProductName,
                    UnitPrice = ShoppingCarts.UnitPrice,
                };
                _context.ShoppingCarts.Add(PTOSCOrder);
            }
            _context.SaveChanges();
            if (notgocart== "notgocart") {
                HttpContext.Session.SetString("notgocart", "已加入購物車!");
                return Redirect($"/CampProducts/ProductDetail?productid={ShoppingCarts.ProductId}"); 
            }
            return Redirect("/PShopCart/Index");//接收的直要呈現在VIEW的檢視頁面/PShopCart/Index
        }
        public IActionResult Index()//檢視：購物車訂單頁面-一開始推進去購物車資料的動作  從購物車資料庫裡抓資料                                
        {

            string userId = HttpContext.Session.GetString("userId") ?? "Guest";
            if (userId == "Guest")
            {
                return Redirect("/Auth/Login");
            }

            CartView returnshCartIndexVM = new CartView()
            {

                ShoppingCarts = _context.ShoppingCarts.Where(x => x.UserId.ToString() == userId),
                Products = _context.Products.ToList(),
                ProductImgs = _context.ProductImgs.ToList(),
                UserName = _context.Users.Find(Convert.ToInt32(userId)).UserName,
                Address = _context.Users.Find(Convert.ToInt32(userId)).Address

            };

            ViewBag.Address = _context.Users.Find(Convert.ToInt32(userId)).Address;
           ViewData["total"] = _context.ShoppingCarts;
            return View("Index", returnshCartIndexVM);
        }
        [HttpPost]
        public IActionResult Index(ShoppingCart temp)//檢視：購物車訂單頁面-購物車商品數量更改後再次推進的動作    
        {
            return View();
        }

        //以下是訂單相關---------------------------------------------------------------------------------------
        [HttpPost]
        public IActionResult OrderIndex(POrderAllModel POrderAllModel)//檢視：改成AddOrder?無-接收購物車清單要傳進訂單資料庫的資料
                                                                      //AddOrder
        {
            Order SCtoOrder = new Order()//推進資料庫Order
            {

Prj_CSharpGo/Views/PShopCart/Index.cshtml
@using Microsoft.AspNetCore.Http

@*@model Prj_CSharpGo.Models.ShopCartViewModels.returnshCartIndexVM*@

@model Prj_CSharpGo.Models.ShopCartViewModels.CartView

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor user
@{
    string f_userId = user.HttpContext.Session.GetString("userId") ?? "1001";
    string shopcart = user.HttpContext.Session.GetString("shopcart");
}

@{
    ViewData["Title"] = "購物車";
}


<main id="main">

    <!-- ======= Intro Single ======= class="intro-single"-->
    <section style="margin-top:60px">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="title-single-box">
                        <h1 class="title-single">購物車</h1>
                    </div>
                </div>
                @*<div class="col-md-12 col-lg-4">
                        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                            <ol class="breadcrumb">

                            </ol>
                        </nav>
                    </div>*@
            </div>
        </div>
    </section><!-- End Intro Single-->
    <!-- ======= Blog Single ======= -->
    <section class="news-single nav-arrow-b">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    @*<h3>購物車清單</h3>*@
                </div>
                <br>

                <input type="hidden" name="UserId" id="UserId" value="@Model.UserId" />
                <table class="table">
                    <thead>
                        <tr class="table-warning">
                            <th scope="col">貨號</th>
                            <th scope="col">圖片</th>
                            <th scope="col">商品名稱</th>
                            <th scope="col">單價</th>
                            <th scope="col"></th>
                            <th scope="col">數量</th>
                            <th scope="col"></th>
                            <th scope="col">小 計</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>

                    <tbody>
                        @{ int i = 1;
                            int? Totall = 0;
                            @foreach (var item in Model.ShoppingCarts)
                            {
                                int? subtotal = item.Quantity * item.UnitPrice;


                                string temp1 = "price" + i;
                                string temp2 = "getUUP" + i;
                                string temp3 = "pricevalue" + i;
                                string temp4 = "before" + i;


                                <tr>
                                    <th scope="row">@item.ProductId</th>
                                    <td>
                                        <img class="card-img rounded-0 img-fluid" style="width:200px;height:200px" src="/img/ProductsImg/@Model.ProductImgs.FirstOrDefault(x => x.ProductId == item.ProductId).Img">
                                    </td>
                                    <td>@item.ProductName</td>  <!--.FirstOrDefault(x => x.ProductId == item.ProductId).ProductName-->
                                    <td id="SHOUP" name="SHOUP">@item.UnitPrice 元</td>

                                    <input type="hidden" name="getUUP" id="@temp2" value="@item.UnitPrice" />


                                    <td style="width: 15px;height:15px">
                                        @*會員手動調整商品數量    應該要推進購物車資料庫裡的數量*@
                                        <div class="col-md-1-4-1">
                                            @using (Html.BeginForm("dash", "PShopCart", FormMethod.Post))//指定提交傳回控制器方式//應該改成AddOrder
                                            {
                                                <input type="hidden" name="ProductId" id="ProductId" value="@item.ProductId" />
                                                <input type="submit" value="-" class="btn btn-success">
                                            }
                                        </div>
                                    </td>

                                    <td style="width: 65px;height:65px;margin:-10px">
                                        <div>
                                            <input class="form-control" name="PQuantity" id="@temp1" value="@item.Quantity" readonly>
                                        </div>
                                    </td>

                                    <td style="width: 15px;height:15px">
                                        <div class="col-md-1-4-1">
                                            @using (Html.BeginForm("plus", "PShopCart", FormMethod.Post))//指定提交傳回控制器方式//應該改成AddOrder
                                            {
                                                <input type="hidden" name="ProductId" id="ProductId" value="@item.ProductId" />
                                                <input type="submit" value="+" class="btn btn-success">
                                            }
                                        </div>
                                    </td>
                                    @*各項單品小計(隨會員更改浮動相乘)@Model.PuserFilterModel.SMTotal*@

                                    <td>
                                        <div id="@temp3">@subtotal 元</div>
                                    </td>

                                    <input type="hidden" id="@temp4" value="" />


                                    <td>
                                        @*總金額(小計相加)@Model.PuserFilterModel.BigTotal =   @<tr id="Total">@Totall 元</tr> *@
                                        @{ Totall += subtotal;}
                                        @using (Html.BeginForm("delete", "PShopCart", FormMethod.Post))//指定提交傳回控制器方式//應該改成AddOrder
                                        {
                                            <input type="hidden" name="ProductId" id="ProductId" value="@item.ProductId" />
                                            <input type="submit" value="刪掉" class="btn btn-secondary">
                                        }
                                    </td>
                                    <td>
                                    </td>

                                </tr>

                                i++;

                            }
                        }

                        <tr class="table-warning">
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col">總金額：</th>
                            <th scope="col"> @Totall 元</th>
                        </tr>

                    </tbody>

                </table>

                <form action="/PShopCart/Bill" method="post">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a href="/CampProducts" type="button" class="btn btn-secondary">再逛逛</a>
                    </div>
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <button id="nowGive1" type="button" class="btn btn-dark">同會員資料</button>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="UserName">收件人名稱</label>
                        <input class="form-control col-sm-9" type="text" data-val="true" data-val-required="不可空白" id="UserName" name="UserName" />
                        <label class="col-sm-3 col-form-label"></label>
                        <span class="text-danger field-validation-valid" data-valmsg-for="UserName" data-valmsg-replace="true"></span>
                    </div>

                    <div class="form-group row">
                        <input id="Address1" type="hidden" value="@Model.Address" />
                        <label class="col-sm-3 col-form-label" for="Address">地址</label>
                        <input class="form-control col-sm-9" type="text" data-val="true" data-val-required="不可空白" id="Address" name="Address" />
                        <label class="col-sm-3 col-form-label"></label>
                        <span class="text-danger field-validation-valid" data-valmsg-for="Address" data-valmsg-replace="true"></span>
                    </div>


                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="PayMethod">付款方式</label>
                        <select name="PayMethod" id="PayMethod" class="form-control col-sm-9">
                            <option value="01">ATM</option>
                            <option value="02">信用卡</option>
                            <option value="03">貨到付款</option>
                        </select>
                    </div>




                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <input type="submit" id="shopend" class="btn btn-success" value="確定">
                    </div>


                </form>
            </div>
        </div>

    </section>
</main><!-- End #main -->
<!-- ======= Footer ======= -->
<!-- Template Main JS File -->
@*<script src="~/js/main.js"></script>*@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">

</script>

@{
    //string userName;
    //string address;

    //foreach (var item in ViewData["User"] as IEnumerable<User>)
    //{
    //    userName = item.UserName;
    //    address = item.Address;
    //}

}

<link href="~/css/emplayout.css?v=0.1" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <link rel="stylesheet" href="~/css/LoginRegister.css">
    <link rel="stylesheet" href="~/css/sb-admin-2.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/toastr.min.js"></script>

@if (shopcart == "購物車沒有東西")
{
    <script type="text/javascript">

        $(function () {

        Command: toastr["error"]("@shopcart");
        @{user.HttpContext.Session.Remove("shopcart");}

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    })
    </script>
}

<script>

    $("#nowGive1").click(function (event) {


        $("#UserName").val("@Model.UserName");
        $("#Address").val($("#Address1").val());

    });

</script>

Prj_CSharpGo/Views/PShopCart/OrderIndex.cshtml
@using Microsoft.AspNetCore.Http
@model Prj_CSharpGo.Models.ShopCartViewModels.POrderAllModel


@{
    ViewData["Title"] = "訂單頁面";

}

<main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="title-single-box">
                        <h1 class="title-single">訂單頁面</h1>
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Book Cover Deisgn
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section><!-- End Intro Single-->
    <!-- ======= Blog Single ======= -->
    <section class="news-single nav-arrow-b">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h3>訂購清單</h3>
                </div>
                <br>
                <table class="table">
                    <thead>
                        <tr class="table-warning">
                            <th scope="col">訂單編號</th>
                            <th scope="col">會員編號</th>
                            <th scope="col">訂單日期</th>
                            <th scope="col">商品編號</th>
                            <th scope="col">商品名稱</th>
                            <th scope="col">總金額</th>
                            <th scope="col">付款方式</th>
                        </tr>
                    </thead>
                    <tbody>                     
                        <tr>
                            <th scope="row">@Model.OrderId</th>
                            <td>@Model.UserId</td>
                            <td>@Model.OrderDate</td>
                             <td>@Model.ProductId</td>
                            <td>@Model.ProductName</td>
                            <td> $@Model.TotalPrice 元</td>
                            <td> @Model.PayMethod</td>
                        </tr>
                        
                    </tbody>
                </table>

                @*using (Html.BeginForm("SHOPQ", "PuserFilterModel", FormMethod.Post))//指定提交傳回後台控制器方式
                    {

                        @Html.HiddenFor(Model => Model.PuserFilterModel.UserId)
                        @Html.HiddenFor(Model => Model.PuserFilterModel.ProductId)
                        @Html.HiddenFor(Model => Model.PuserFilterModel.ProductName)
                        @Html.HiddenFor(Model => Model.PuserFilterModel.Quantity)
                        @Html.HiddenFor(Model => Model.PuserFilterModel.UnitPrice)
                        @Html.HiddenFor(Model => Model.PuserFilterModel.SMTotal)
                        @Html.HiddenFor(Model => Model.PuserFilterModel.BigTotal)

                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="/Home/Product" type="button" class="btn btn-secondary">再逛逛</a>
                            <a href="/Home/Product" type="submit" class="btn btn-success">去買單</a>

                        </div>
                    }
                *@
            </div>
        </div>
    </section>
</main><!-- End #main -->
<!-- ======= Footer ======= -->
<!-- Template Main JS File -->
@*<script src="~/js/main.js"></script>*@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">

</script>
<script>

        $("#comform").click(function () {
            alert('@Html.Raw(ViewBag.messagea)');
         });

</script>